# Generated by Django 6.0.3 on 2026-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='images',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
