# Generated by Django 6.0.3 on 2026-03-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_channel_images_delete_mymodel_delete_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.AddField(
            model_name='video',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='videos', to='youtube.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='youtube.category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='checkout',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='youtube.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='checkout',
            field=models.DateTimeField(db_index=True),
        ),
    ]
