# Generated by Django 6.0.3 on 2026-03-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_playlist_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='checkout',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
