# Generated by Django 6.0.3 on 2026-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_channel_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='next_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
